name: bruno
description: An enterprise-class package of Flutter components for mobile applications.
version: 3.0.0
homepage: https://github.com/LianjiaTech/bruno

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0
  lpinyin: ^2.0.3
  path_drawing: ^1.0.0
  flutter_easyrefresh: ^2.2.1
  intl: ^0.17.0
  photo_view: ^0.14.0
  badges: ^2.0.2
  bindings_compatible: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/radio/
    - assets/images/no_data.png
    - assets/images/two_line_bubble.png
    - assets/json/
    - assets/json/china.json
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Bebas
       fonts:
         - asset: assets/fonts/Bebas-Regular.ttf
#           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
